/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'checkIn' : IDL.Text,
  'createdAt' : IDL.Int,
  'guestName' : IDL.Text,
  'checkOut' : IDL.Text,
  'phone' : IDL.Text,
  'roomId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'pricePerNight' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'available' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactPhone' : IDL.Func([], [IDL.Text], ['query']),
  'getRoomById' : IDL.Func([IDL.Nat], [Room], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBooking' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'updateContactPhone' : IDL.Func([IDL.Text], [], []),
  'updateRoom' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'checkIn' : IDL.Text,
    'createdAt' : IDL.Int,
    'guestName' : IDL.Text,
    'checkOut' : IDL.Text,
    'phone' : IDL.Text,
    'roomId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'pricePerNight' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'available' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactPhone' : IDL.Func([], [IDL.Text], ['query']),
    'getRoomById' : IDL.Func([IDL.Nat], [Room], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBooking' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'updateContactPhone' : IDL.Func([IDL.Text], [], []),
    'updateRoom' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };